[package]
name = "randomTheme"
version = "0.1.0"
edition = "2021"


[dependencies]
dirs = "5.0.1"
rand = "0.8.4"
reqwest = "0.11.24"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
